name: Update Pac-Man contribution graph

on:
  schedule:
    - cron: '17 2 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Generate Pac-Man animations
        uses: abozanona/pacman-contribution-graph@v5.3.2
        with:
          github_user_name: ${{ github.repository_owner }}
          games: pacman

      - name: Publish Pac-Man animations
        uses: crazy-max/ghaction-github-pages@v5
        with:
          target_branch: output
          build_dir: dist
          commit_message: 'Update Pac-Man contribution graph'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
